# General
KMER: 6
LABELS_TO_USE: "GISAID" # Options: "GISAID", "Pango"
MIN_SAMPLES_LABEL: 1000 # minimum samples per label
MAX_SAMPLES_LABEL: 100_000

# --- FCGR ---
# priority CANONICAL_KMERS > SPACED_KMERS > ALL KMERS
# if both CANONICAL_KMERS and SPACED_KMERS are set to False, FCGR will be generated 
# considering all kmers
CANONICAL_KMERS: True

# spaced-kmers will be used only if CANONICAL_KMERS is set to False
SPACED_KMERS: False # if True, PATH_KMER_COUNT must have larger kmers than KMER (of length equal to the SPACED_PATTERN string)
SPACED_PATTERN: "##-###--#" # used if SPACED_KMER is True, "#": match character, "-": ommited character

# INPUT DATA
PATH_KMER_COUNT: "/home/jorge/samples-sars-cov2/6mers"
PATH_LABELS: "data/clean_labels.tsv" #"/home/jorge/samples-sars-cov2/srrgis.clade.csv"

# MODEL
EMBEDDING_SIZE: 100 # output of trained model
TRAIN_SIZE: 0.8 # size for val and test sets: (1-TRAIN_SIZE)/2
BATCH_SIZE: 128
EPOCHS: 200
PREPROCESSING: {"divide_by_max": {}} # ("name_function", dict_kwargs)
WEIGHTS_PATH: null #/home/jorge/CouGaR-s/data/train/checkpoints/weights-36-0.062.hdf5 # null

# REPRODUCIBILITY
SEED: 42

# callbacks early stopping
PATIENTE_EARLY_STOPPING: 50 # stop training after N epochs without improvement
PATIENTE_REDUCE_LR: 30 # reduce learning rate after N epochs without improvement