# General
KMER: 6
CANONICAL_KMERS: True
LABELS_TO_USE: "GISAID" # Options: "GISAID", "Pango"

# INPUT DATA
PATH_KMER_COUNT: ""
PATH_LABELS: ""

# MODEL
EMBEDDING_SIZE: 100
TRAIN_SIZE: 0.8 # size for val and test sets: (1-TRAIN_SIZE)/2
BATCH_SIZE: 16
EPOCHS: 50
PREPROCESSING: {"divide_by_max": {}} # ("name_function", dict_kwargs)
WEIGHTS_PATH: null

# REPRODUCIBILITY
SEED: 42

# callbacks early stopping
PATIENTE_EARLY_STOPPING: 20 # stop training after N epochs without improvement
PATIENTE_REDUCE_LR: 15 # reduce learning rate after N epochs without improvement